
// This file is automatically generated by stac init.

import 'package:stac_core/core/stac_options.dart';

/// Default [StacOptions] for use with your stac project.
///
/// Use this to initialize stac **before** calling [runApp].
///
/// Example:
/// ```dart
/// import 'package:flutter/material.dart';
/// import 'package:stac/stac.dart';
/// import 'default_stac_options.dart';
///
/// void main() {
///   Stac.initialize(options: defaultStacOptions);
///
///   runApp(...);
/// }
/// ```
StacOptions get defaultStacOptions => StacOptions(
  name: 'sdui_stac',
  description: 'null',
  projectId: 'rFSzfi8KyI2fdEKGIywU',
);
